model: mistralai/Voxtral-Mini-3B-2507
checkpoint_path: mistralai/Voxtral-Mini-3B-2507
lang: ms
manifest: /home/pumba-04/Desktop/MEGAN/datasets/MOOFOO_S2TT/ms_test_manifest_updated.json
output_path: ./eval_results/vox_3B_pretrained_asr_ms_test.json