model: mistralai/Voxtral-Mini-3B-2507
checkpoint_path: mistralai/Voxtral-Mini-3B-2507
lang: null # set to `null` if want to read from manifest source.lang
manifest: /home/pumba-04/Desktop/MEGAN/datasets/MOOFOO_S2TT/v3_test.json
output_path: ./eval_results/testtest.json
device: 1