model: mistralai/Voxtral-Mini-3B-2507
checkpoint_path: /home/pumba-03/Desktop/megan/models/voxtral_multitask_st_asr_v4/checkpoint-55000
lang: id
manifest: /home/pumba-03/Desktop/megan/data/moofoo/id_test_manifest_multitask.json
output_path: ./eval_results/ASR_3B_pretrained_id_test.json
device: 0