model: mistralai/Voxtral-Mini-3B-2507
checkpoint_path: /home/pumba-03/Desktop/megan/models/voxtral_multitask_st_asr_v4/checkpoint-55000
manifest: /home/pumba-03/Desktop/megan/data/moofoo/ms_test_manifest.json
output_path: ./eval_results/3B_v4_ms_eval.json
device: 1