model: mistralai/Voxtral-Mini-3B-2507
checkpoint_path: /home/pumba-04/Desktop/MEGAN/code/voxtral-finetuning/experiments/s2tt_asr_multitask_dataset_v3_class_weight_multi_gpu_20251205_173525/checkpoint-39016
lang: null
manifest: /home/pumba-04/Desktop/MEGAN/datasets/MOOFOO_S2TT/v3_test.json
output_path: ./eval_results/testtest.json
device: 1